"""
Program database models.

Defines the Program (template) structure with associated weeks, days, and exercises.
Programs are generated by builders and can be saved as templates or assigned to clients.
"""
from sqlalchemy import Column, String, Boolean, Integer, Float, ForeignKey, Index, Text
from sqlalchemy.orm import relationship
from app.models.base import BaseModel, GUID
from app.models.subscription import JSONBType


class Program(BaseModel):
    """
    Program model representing workout programs/templates.

    Programs are generated from builders (e.g., Strength Linear 5x5) and can be:
    1. Saved as templates in the template library
    2. Assigned to clients for tracking
    3. Shared publicly in the marketplace (future)

    Attributes:
        subscription_id: Foreign key to subscription (null for public templates)
        created_by_user_id: User who created this program
        name: Program name (e.g., "8-Week Linear Strength")
        description: Optional description
        builder_type: Type of builder used (e.g., "strength_linear_5x5")
        algorithm_version: Version of algorithm used to generate (e.g., "v1.0.0")
        input_data: JSONB with original inputs (for regeneration)
        calculated_data: JSONB with calculated values (weekly jumps, ramp-up, etc.)
        is_template: Whether this is a template (true) or client assignment (false)
        is_public: Whether visible in marketplace (future feature)
        duration_weeks: Total weeks in program
        days_per_week: Training sessions per week

    Inherits from BaseModel:
        id: Primary key (UUID)
        created_at: When program was created
        created_by: User ID who created (audit trail)
        updated_at: Last modification timestamp
        updated_by: User ID who last updated

    Database Relationships:
        - weeks: One-to-many with ProgramWeek (cascade delete)
        - Subscription (many-to-one)
    """
    __tablename__ = "programs"

    # Subscription and creator
    subscription_id = Column(
        GUID,
        ForeignKey('subscriptions.id', ondelete='CASCADE'),
        nullable=True,  # Null for public templates
        index=True,
        doc="Foreign key to subscription (null for public templates)"
    )

    created_by_user_id = Column(
        GUID,
        ForeignKey('users.id', ondelete='SET NULL'),
        nullable=True,  # Null if user is deleted
        index=True,
        doc="User who created this program"
    )

    # Program metadata
    name = Column(
        String(255),
        nullable=False,
        doc="Program name (e.g., '8-Week Linear Strength')"
    )

    description = Column(
        Text,
        nullable=True,
        doc="Optional program description"
    )

    builder_type = Column(
        String(100),
        nullable=False,
        index=True,
        doc="Builder type (e.g., 'strength_linear_5x5')"
    )

    algorithm_version = Column(
        String(50),
        nullable=False,
        doc="Algorithm version used (e.g., 'v1.0.0')"
    )

    # Program data (stored as JSONB for flexibility)
    input_data = Column(
        JSONBType,
        nullable=False,
        doc="Original inputs (movements, 1RMs, target weights, etc.)"
    )

    calculated_data = Column(
        JSONBType,
        nullable=True,
        doc="Calculated values (weekly jumps, ramp-up percentages, etc.)"
    )

    # Template flags
    is_template = Column(
        Boolean,
        default=True,
        nullable=False,
        index=True,
        doc="Whether this is a template (true) or client assignment (false)"
    )

    is_public = Column(
        Boolean,
        default=False,
        nullable=False,
        index=True,
        doc="Whether visible in marketplace (future feature)"
    )

    # Program structure
    duration_weeks = Column(
        Integer,
        nullable=False,
        doc="Total weeks in program"
    )

    days_per_week = Column(
        Integer,
        nullable=False,
        doc="Training sessions per week"
    )

    # Relationships
    weeks = relationship(
        "ProgramWeek",
        back_populates="program",
        cascade="all, delete-orphan",
        order_by="ProgramWeek.week_number"
    )

    # Composite indexes for common queries
    __table_args__ = (
        # Index for template library queries
        Index('ix_programs_subscription_template', 'subscription_id', 'is_template'),
        # Index for marketplace queries (future)
        Index('ix_programs_public_builder', 'is_public', 'builder_type'),
        # Index for creator queries
        Index('ix_programs_creator_template', 'created_by_user_id', 'is_template'),
    )

    def __repr__(self) -> str:
        """String representation for debugging."""
        return f"<Program(id={self.id}, name='{self.name}', builder_type='{self.builder_type}')>"


class ProgramWeek(BaseModel):
    """
    ProgramWeek model representing individual weeks in a program.

    Attributes:
        program_id: Foreign key to parent program
        week_number: Week number (1-8)
        name: Descriptive name (e.g., "Foundation Phase", "Peak Phase")

    Inherits from BaseModel:
        id, created_at, created_by, updated_at, updated_by

    Database Relationships:
        - program: Many-to-one with Program
        - days: One-to-many with ProgramDay (cascade delete)
    """
    __tablename__ = "program_weeks"

    program_id = Column(
        GUID,
        ForeignKey('programs.id', ondelete='CASCADE'),
        nullable=False,
        index=True,
        doc="Foreign key to parent program"
    )

    week_number = Column(
        Integer,
        nullable=False,
        doc="Week number (1-based)"
    )

    name = Column(
        String(255),
        nullable=False,
        doc="Week name (e.g., 'Foundation Phase')"
    )

    # Relationships
    program = relationship("Program", back_populates="weeks")
    days = relationship(
        "ProgramDay",
        back_populates="week",
        cascade="all, delete-orphan",
        order_by="ProgramDay.day_number"
    )

    # Composite indexes
    __table_args__ = (
        # Unique constraint: one week number per program
        Index('ix_program_weeks_program_week', 'program_id', 'week_number', unique=True),
    )

    def __repr__(self) -> str:
        """String representation for debugging."""
        return f"<ProgramWeek(id={self.id}, program_id={self.program_id}, week={self.week_number}, name='{self.name}')>"


class ProgramDay(BaseModel):
    """
    ProgramDay model representing individual training days.

    Attributes:
        program_week_id: Foreign key to parent week
        day_number: Day number within week (1-4 typically)
        name: Day name (e.g., "Session 1 - Heavy Day")
        suggested_day_of_week: Optional suggested day (e.g., "Monday")

    Inherits from BaseModel:
        id, created_at, created_by, updated_at, updated_by

    Database Relationships:
        - week: Many-to-one with ProgramWeek
        - exercises: One-to-many with ProgramDayExercise (cascade delete)
    """
    __tablename__ = "program_days"

    program_week_id = Column(
        GUID,
        ForeignKey('program_weeks.id', ondelete='CASCADE'),
        nullable=False,
        index=True,
        doc="Foreign key to parent week"
    )

    day_number = Column(
        Integer,
        nullable=False,
        doc="Day number within week (1-based)"
    )

    name = Column(
        String(255),
        nullable=False,
        doc="Day name (e.g., 'Session 1 - Heavy Day')"
    )

    suggested_day_of_week = Column(
        String(50),
        nullable=True,
        doc="Suggested day of week (e.g., 'Monday')"
    )

    # Relationships
    week = relationship("ProgramWeek", back_populates="days")
    exercises = relationship(
        "ProgramDayExercise",
        back_populates="day",
        cascade="all, delete-orphan",
        order_by="ProgramDayExercise.order"
    )

    # Composite indexes
    __table_args__ = (
        # Unique constraint: one day number per week
        Index('ix_program_days_week_day', 'program_week_id', 'day_number', unique=True),
    )

    def __repr__(self) -> str:
        """String representation for debugging."""
        return f"<ProgramDay(id={self.id}, week_id={self.program_week_id}, day={self.day_number}, name='{self.name}')>"


class ProgramDayExercise(BaseModel):
    """
    ProgramDayExercise model representing exercises within a training day.

    Attributes:
        program_day_id: Foreign key to parent day
        exercise_name: Name of exercise (e.g., "SQUAT", "squat")
        sets: Number of sets
        reps: Number of reps per set
        weight_lbs: Prescribed weight in lbs (null for testing week)
        percentage_1rm: Percentage of 1RM (null for testing week)
        notes: Optional notes/instructions
        order: Display order within day

    Inherits from BaseModel:
        id, created_at, created_by, updated_at, updated_by

    Database Relationships:
        - day: Many-to-one with ProgramDay
    """
    __tablename__ = "program_day_exercises"

    program_day_id = Column(
        GUID,
        ForeignKey('program_days.id', ondelete='CASCADE'),
        nullable=False,
        index=True,
        doc="Foreign key to parent day"
    )

    exercise_name = Column(
        String(255),
        nullable=False,
        index=True,
        doc="Exercise name (uppercase for heavy, lowercase for light)"
    )

    sets = Column(
        Integer,
        nullable=False,
        doc="Number of sets"
    )

    reps = Column(
        Integer,
        nullable=False,
        doc="Number of reps per set"
    )

    weight_lbs = Column(
        Integer,
        nullable=True,
        doc="Prescribed weight in lbs (null for testing week)"
    )

    percentage_1rm = Column(
        Integer,
        nullable=True,
        doc="Percentage of 1RM (null if not applicable)"
    )

    notes = Column(
        Text,
        nullable=True,
        doc="Optional notes/instructions"
    )

    order = Column(
        Integer,
        nullable=False,
        default=0,
        doc="Display order within day (0-based)"
    )

    # Relationships
    day = relationship("ProgramDay", back_populates="exercises")

    # Composite indexes
    __table_args__ = (
        # Index for day + order queries
        Index('ix_program_day_exercises_day_order', 'program_day_id', 'order'),
        # Index for exercise name searches
        Index('ix_program_day_exercises_name', 'exercise_name'),
    )

    def __repr__(self) -> str:
        """String representation for debugging."""
        return f"<ProgramDayExercise(id={self.id}, exercise='{self.exercise_name}', sets={self.sets}, reps={self.reps}, weight={self.weight_lbs})>"
