"""initial_schema

Revision ID: 0860cfe8f6ce
Revises: 
Create Date: 2026-02-18 12:02:17.532597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0860cfe8f6ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subscription_type', sa.Enum('INDIVIDUAL', 'GYM', 'ENTERPRISE', name='subscription_type_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELLED', name='subscription_status_enum', native_enum=False), nullable=False),
    sa.Column('features', app.models.subscription.JSONBType(), nullable=False),
    sa.Column('limits', app.models.subscription.JSONBType(), nullable=False),
    sa.Column('billing_info', app.models.subscription.JSONBType(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', app.models.base.GUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_name'), 'subscriptions', ['name'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscription_type'), 'subscriptions', ['subscription_type'], unique=False)
    op.create_table('exercises_library',
    sa.Column('subscription_id', app.models.base.GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('muscle_groups', app.models.subscription.JSONBType(), nullable=False),
    sa.Column('equipment', app.models.subscription.JSONBType(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('is_bilateral', sa.Boolean(), nullable=False),
    sa.Column('is_timed', sa.Boolean(), nullable=False),
    sa.Column('default_rest_seconds', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('progression_exercises', app.models.subscription.JSONBType(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', app.models.base.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercises_category', 'exercises_library', ['category'], unique=False)
    op.create_index('ix_exercises_global_active', 'exercises_library', ['is_global', 'is_active'], unique=False)
    op.create_index(op.f('ix_exercises_library_category'), 'exercises_library', ['category'], unique=False)
    op.create_index(op.f('ix_exercises_library_id'), 'exercises_library', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_library_is_active'), 'exercises_library', ['is_active'], unique=False)
    op.create_index(op.f('ix_exercises_library_is_global'), 'exercises_library', ['is_global'], unique=False)
    op.create_index(op.f('ix_exercises_library_name'), 'exercises_library', ['name'], unique=False)
    op.create_index(op.f('ix_exercises_library_subscription_id'), 'exercises_library', ['subscription_id'], unique=False)
    op.create_index('ix_exercises_subscription_active', 'exercises_library', ['subscription_id', 'is_active'], unique=False)
    op.create_table('locations',
    sa.Column('subscription_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', app.models.subscription.JSONBType(), nullable=True),
    sa.Column('contact_info', app.models.subscription.JSONBType(), nullable=True),
    sa.Column('settings', app.models.subscription.JSONBType(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', app.models.base.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index('ix_locations_subscription_active', 'locations', ['subscription_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_locations_subscription_id'), 'locations', ['subscription_id'], unique=False)
    op.create_table('users',
    sa.Column('subscription_id', app.models.base.GUID(), nullable=True),
    sa.Column('location_id', app.models.base.GUID(), nullable=True),
    sa.Column('role', sa.Enum('APPLICATION_SUPPORT', 'SUBSCRIPTION_ADMIN', 'COACH', 'CLIENT', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile', app.models.subscription.JSONBType(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_must_be_changed', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', app.models.base.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_location_id'), 'users', ['location_id'], unique=False)
    op.create_index('ix_users_location_role', 'users', ['location_id', 'role'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_subscription_active', 'users', ['subscription_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_subscription_id'), 'users', ['subscription_id'], unique=False)
    op.create_index('ix_users_subscription_role', 'users', ['subscription_id', 'role'], unique=False)
    op.create_table('audit_log',
    sa.Column('subscription_id', app.models.base.GUID(), nullable=True),
    sa.Column('location_id', app.models.base.GUID(), nullable=True),
    sa.Column('user_id', app.models.base.GUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'ACCESS', 'PERMISSION_DENIED', 'PASSWORD_RESET', 'ROLE_CHANGE', name='audit_action_enum', native_enum=False), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', app.models.base.GUID(), nullable=True),
    sa.Column('changes', app.models.subscription.JSONBType(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('extra_metadata', app.models.subscription.JSONBType(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', app.models.base.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_timestamp', 'audit_log', ['action', 'timestamp'], unique=False)
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_location_id'), 'audit_log', ['location_id'], unique=False)
    op.create_index(op.f('ix_audit_log_subscription_id'), 'audit_log', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_index('ix_audit_subscription_timestamp', 'audit_log', ['subscription_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_user_timestamp', 'audit_log', ['user_id', 'timestamp'], unique=False)
    op.create_table('coach_client_assignments',
    sa.Column('subscription_id', app.models.base.GUID(), nullable=False),
    sa.Column('location_id', app.models.base.GUID(), nullable=True),
    sa.Column('coach_id', app.models.base.GUID(), nullable=False),
    sa.Column('client_id', app.models.base.GUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', app.models.base.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coach_client_assignments_client_active', 'coach_client_assignments', ['client_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_coach_client_assignments_client_id'), 'coach_client_assignments', ['client_id'], unique=False)
    op.create_index('ix_coach_client_assignments_coach_active', 'coach_client_assignments', ['coach_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_coach_client_assignments_coach_id'), 'coach_client_assignments', ['coach_id'], unique=False)
    op.create_index(op.f('ix_coach_client_assignments_id'), 'coach_client_assignments', ['id'], unique=False)
    op.create_index('ix_coach_client_assignments_location_active', 'coach_client_assignments', ['location_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_coach_client_assignments_location_id'), 'coach_client_assignments', ['location_id'], unique=False)
    op.create_index('ix_coach_client_assignments_subscription_active', 'coach_client_assignments', ['subscription_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_coach_client_assignments_subscription_id'), 'coach_client_assignments', ['subscription_id'], unique=False)
    op.create_index('ix_coach_client_assignments_unique', 'coach_client_assignments', ['coach_id', 'client_id', 'is_active'], unique=True)
    op.create_table('programs',
    sa.Column('subscription_id', app.models.base.GUID(), nullable=True),
    sa.Column('created_by_user_id', app.models.base.GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('program_type', sa.String(length=50), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('builder_type', sa.String(length=100), nullable=True),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.Column('input_data', app.models.subscription.JSONBType(), nullable=True),
    sa.Column('calculated_data', app.models.subscription.JSONBType(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('parent_template_id', app.models.base.GUID(), nullable=True),
    sa.Column('required_parameters', app.models.subscription.JSONBType(), nullable=False),
    sa.Column('optional_parameters', app.models.subscription.JSONBType(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('tags', app.models.subscription.JSONBType(), nullable=False),
    sa.Column('goals', app.models.subscription.JSONBType(), nullable=True),
    sa.Column('target_gender', sa.String(length=20), nullable=True),
    sa.Column('equipment_required', app.models.subscription.JSONBType(), nullable=True),
    sa.Column('times_assigned', sa.Integer(), nullable=False),
    sa.Column('average_completion_rate', sa.Float(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('revenue_share_pct', sa.Float(), nullable=True),
    sa.Column('archived_at', sa.String(length=50), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', app.models.base.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_template_id'], ['programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_builder_type'), 'programs', ['builder_type'], unique=False)
    op.create_index(op.f('ix_programs_created_by_user_id'), 'programs', ['created_by_user_id'], unique=False)
    op.create_index('ix_programs_creator_template', 'programs', ['created_by_user_id', 'is_template'], unique=False)
    op.create_index('ix_programs_default_type', 'programs', ['is_default', 'program_type'], unique=False)
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_index(op.f('ix_programs_is_default'), 'programs', ['is_default'], unique=False)
    op.create_index(op.f('ix_programs_is_public'), 'programs', ['is_public'], unique=False)
    op.create_index(op.f('ix_programs_is_template'), 'programs', ['is_template'], unique=False)
    op.create_index(op.f('ix_programs_program_type'), 'programs', ['program_type'], unique=False)
    op.create_index('ix_programs_public_type', 'programs', ['is_public', 'program_type'], unique=False)
    op.create_index(op.f('ix_programs_subscription_id'), 'programs', ['subscription_id'], unique=False)
    op.create_index('ix_programs_subscription_template', 'programs', ['subscription_id', 'is_template'], unique=False)
    op.create_table('client_program_assignments',
    sa.Column('subscription_id', app.models.base.GUID(), nullable=False),
    sa.Column('location_id', app.models.base.GUID(), nullable=True),
    sa.Column('coach_id', app.models.base.GUID(), nullable=True),
    sa.Column('client_id', app.models.base.GUID(), nullable=False),
    sa.Column('program_id', app.models.base.GUID(), nullable=False),
    sa.Column('assignment_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', app.models.base.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_assignments_client_active', 'client_program_assignments', ['client_id', 'is_active', 'status'], unique=False)
    op.create_index('ix_client_assignments_coach', 'client_program_assignments', ['coach_id', 'is_active'], unique=False)
    op.create_index('ix_client_assignments_location', 'client_program_assignments', ['location_id', 'is_active'], unique=False)
    op.create_index('ix_client_assignments_status_dates', 'client_program_assignments', ['status', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_client_assignments_subscription', 'client_program_assignments', ['subscription_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_client_program_assignments_client_id'), 'client_program_assignments', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_program_assignments_coach_id'), 'client_program_assignments', ['coach_id'], unique=False)
    op.create_index(op.f('ix_client_program_assignments_id'), 'client_program_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_client_program_assignments_is_active'), 'client_program_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_client_program_assignments_location_id'), 'client_program_assignments', ['location_id'], unique=False)
    op.create_index(op.f('ix_client_program_assignments_program_id'), 'client_program_assignments', ['program_id'], unique=False)
    op.create_index(op.f('ix_client_program_assignments_status'), 'client_program_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_client_program_assignments_subscription_id'), 'client_program_assignments', ['subscription_id'], unique=False)
    op.create_table('program_assignments',
    sa.Column('subscription_id', app.models.base.GUID(), nullable=False),
    sa.Column('template_id', app.models.base.GUID(), nullable=False),
    sa.Column('client_id', app.models.base.GUID(), nullable=False),
    sa.Column('assigned_by', app.models.base.GUID(), nullable=True),
    sa.Column('program_id', app.models.base.GUID(), nullable=False),
    sa.Column('assignment_parameters', app.models.subscription.JSONBType(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('workouts_completed', sa.Integer(), nullable=False),
    sa.Column('workouts_total', sa.Integer(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('client_rating', sa.Float(), nullable=True),
    sa.Column('client_feedback', sa.Text(), nullable=True),
    sa.Column('coach_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', app.models.base.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['programs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_program_assignments_client_active', 'program_assignments', ['client_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_program_assignments_client_id'), 'program_assignments', ['client_id'], unique=False)
    op.create_index(op.f('ix_program_assignments_id'), 'program_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_program_assignments_is_active'), 'program_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_program_assignments_program_id'), 'program_assignments', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_assignments_start_date'), 'program_assignments', ['start_date'], unique=False)
    op.create_index(op.f('ix_program_assignments_status'), 'program_assignments', ['status'], unique=False)
    op.create_index('ix_program_assignments_status_active', 'program_assignments', ['status', 'is_active'], unique=False)
    op.create_index('ix_program_assignments_subscription', 'program_assignments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_program_assignments_subscription_id'), 'program_assignments', ['subscription_id'], unique=False)
    op.create_index('ix_program_assignments_template', 'program_assignments', ['template_id'], unique=False)
    op.create_index(op.f('ix_program_assignments_template_id'), 'program_assignments', ['template_id'], unique=False)
    op.create_table('program_weeks',
    sa.Column('program_id', app.models.base.GUID(), nullable=False),
    sa.Column('subscription_id', app.models.base.GUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('focus_area', sa.String(length=100), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', app.models.base.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_weeks_id'), 'program_weeks', ['id'], unique=False)
    op.create_index(op.f('ix_program_weeks_program_id'), 'program_weeks', ['program_id'], unique=False)
    op.create_index('ix_program_weeks_program_week', 'program_weeks', ['program_id', 'week_number'], unique=True)
    op.create_index(op.f('ix_program_weeks_subscription_id'), 'program_weeks', ['subscription_id'], unique=False)
    op.create_table('program_days',
    sa.Column('program_week_id', app.models.base.GUID(), nullable=False),
    sa.Column('subscription_id', app.models.base.GUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('day_type', sa.String(length=50), nullable=True),
    sa.Column('suggested_day_of_week', sa.Integer(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('warm_up_notes', sa.Text(), nullable=True),
    sa.Column('cool_down_notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', app.models.base.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['program_week_id'], ['program_weeks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_days_id'), 'program_days', ['id'], unique=False)
    op.create_index(op.f('ix_program_days_program_week_id'), 'program_days', ['program_week_id'], unique=False)
    op.create_index(op.f('ix_program_days_subscription_id'), 'program_days', ['subscription_id'], unique=False)
    op.create_index('ix_program_days_week_day', 'program_days', ['program_week_id', 'day_number'], unique=True)
    op.create_table('program_day_exercises',
    sa.Column('program_day_id', app.models.base.GUID(), nullable=False),
    sa.Column('exercise_id', app.models.base.GUID(), nullable=True),
    sa.Column('exercise_name', sa.String(length=255), nullable=True),
    sa.Column('subscription_id', app.models.base.GUID(), nullable=True),
    sa.Column('exercise_order', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps_min', sa.Integer(), nullable=True),
    sa.Column('reps_max', sa.Integer(), nullable=True),
    sa.Column('reps_target', sa.Integer(), nullable=True),
    sa.Column('load_type', sa.String(length=50), nullable=True),
    sa.Column('load_value', sa.Float(), nullable=True),
    sa.Column('load_unit', sa.String(length=20), nullable=True),
    sa.Column('tempo', sa.String(length=20), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rpe_target', sa.Float(), nullable=True),
    sa.Column('percentage_1rm', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('coaching_cues', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('actual_sets', sa.Integer(), nullable=True),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('actual_weight', sa.Float(), nullable=True),
    sa.Column('actual_rpe', sa.Float(), nullable=True),
    sa.Column('completion_date', sa.String(length=50), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', app.models.base.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises_library.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_program_day_exercises_day_order', 'program_day_exercises', ['program_day_id', 'exercise_order'], unique=False)
    op.create_index('ix_program_day_exercises_exercise', 'program_day_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_program_day_exercises_exercise_id'), 'program_day_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_program_day_exercises_id'), 'program_day_exercises', ['id'], unique=False)
    op.create_index(op.f('ix_program_day_exercises_program_day_id'), 'program_day_exercises', ['program_day_id'], unique=False)
    op.create_index(op.f('ix_program_day_exercises_subscription_id'), 'program_day_exercises', ['subscription_id'], unique=False)
    op.create_index('ix_program_day_exercises_unique_order', 'program_day_exercises', ['program_day_id', 'exercise_order'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_program_day_exercises_unique_order', table_name='program_day_exercises')
    op.drop_index(op.f('ix_program_day_exercises_subscription_id'), table_name='program_day_exercises')
    op.drop_index(op.f('ix_program_day_exercises_program_day_id'), table_name='program_day_exercises')
    op.drop_index(op.f('ix_program_day_exercises_id'), table_name='program_day_exercises')
    op.drop_index(op.f('ix_program_day_exercises_exercise_id'), table_name='program_day_exercises')
    op.drop_index('ix_program_day_exercises_exercise', table_name='program_day_exercises')
    op.drop_index('ix_program_day_exercises_day_order', table_name='program_day_exercises')
    op.drop_table('program_day_exercises')
    op.drop_index('ix_program_days_week_day', table_name='program_days')
    op.drop_index(op.f('ix_program_days_subscription_id'), table_name='program_days')
    op.drop_index(op.f('ix_program_days_program_week_id'), table_name='program_days')
    op.drop_index(op.f('ix_program_days_id'), table_name='program_days')
    op.drop_table('program_days')
    op.drop_index(op.f('ix_program_weeks_subscription_id'), table_name='program_weeks')
    op.drop_index('ix_program_weeks_program_week', table_name='program_weeks')
    op.drop_index(op.f('ix_program_weeks_program_id'), table_name='program_weeks')
    op.drop_index(op.f('ix_program_weeks_id'), table_name='program_weeks')
    op.drop_table('program_weeks')
    op.drop_index(op.f('ix_program_assignments_template_id'), table_name='program_assignments')
    op.drop_index('ix_program_assignments_template', table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_subscription_id'), table_name='program_assignments')
    op.drop_index('ix_program_assignments_subscription', table_name='program_assignments')
    op.drop_index('ix_program_assignments_status_active', table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_status'), table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_start_date'), table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_program_id'), table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_is_active'), table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_id'), table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_client_id'), table_name='program_assignments')
    op.drop_index('ix_program_assignments_client_active', table_name='program_assignments')
    op.drop_table('program_assignments')
    op.drop_index(op.f('ix_client_program_assignments_subscription_id'), table_name='client_program_assignments')
    op.drop_index(op.f('ix_client_program_assignments_status'), table_name='client_program_assignments')
    op.drop_index(op.f('ix_client_program_assignments_program_id'), table_name='client_program_assignments')
    op.drop_index(op.f('ix_client_program_assignments_location_id'), table_name='client_program_assignments')
    op.drop_index(op.f('ix_client_program_assignments_is_active'), table_name='client_program_assignments')
    op.drop_index(op.f('ix_client_program_assignments_id'), table_name='client_program_assignments')
    op.drop_index(op.f('ix_client_program_assignments_coach_id'), table_name='client_program_assignments')
    op.drop_index(op.f('ix_client_program_assignments_client_id'), table_name='client_program_assignments')
    op.drop_index('ix_client_assignments_subscription', table_name='client_program_assignments')
    op.drop_index('ix_client_assignments_status_dates', table_name='client_program_assignments')
    op.drop_index('ix_client_assignments_location', table_name='client_program_assignments')
    op.drop_index('ix_client_assignments_coach', table_name='client_program_assignments')
    op.drop_index('ix_client_assignments_client_active', table_name='client_program_assignments')
    op.drop_table('client_program_assignments')
    op.drop_index('ix_programs_subscription_template', table_name='programs')
    op.drop_index(op.f('ix_programs_subscription_id'), table_name='programs')
    op.drop_index('ix_programs_public_type', table_name='programs')
    op.drop_index(op.f('ix_programs_program_type'), table_name='programs')
    op.drop_index(op.f('ix_programs_is_template'), table_name='programs')
    op.drop_index(op.f('ix_programs_is_public'), table_name='programs')
    op.drop_index(op.f('ix_programs_is_default'), table_name='programs')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_index('ix_programs_default_type', table_name='programs')
    op.drop_index('ix_programs_creator_template', table_name='programs')
    op.drop_index(op.f('ix_programs_created_by_user_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_builder_type'), table_name='programs')
    op.drop_table('programs')
    op.drop_index('ix_coach_client_assignments_unique', table_name='coach_client_assignments')
    op.drop_index(op.f('ix_coach_client_assignments_subscription_id'), table_name='coach_client_assignments')
    op.drop_index('ix_coach_client_assignments_subscription_active', table_name='coach_client_assignments')
    op.drop_index(op.f('ix_coach_client_assignments_location_id'), table_name='coach_client_assignments')
    op.drop_index('ix_coach_client_assignments_location_active', table_name='coach_client_assignments')
    op.drop_index(op.f('ix_coach_client_assignments_id'), table_name='coach_client_assignments')
    op.drop_index(op.f('ix_coach_client_assignments_coach_id'), table_name='coach_client_assignments')
    op.drop_index('ix_coach_client_assignments_coach_active', table_name='coach_client_assignments')
    op.drop_index(op.f('ix_coach_client_assignments_client_id'), table_name='coach_client_assignments')
    op.drop_index('ix_coach_client_assignments_client_active', table_name='coach_client_assignments')
    op.drop_table('coach_client_assignments')
    op.drop_index('ix_audit_user_timestamp', table_name='audit_log')
    op.drop_index('ix_audit_subscription_timestamp', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_subscription_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_location_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_index('ix_audit_action_timestamp', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_users_subscription_role', table_name='users')
    op.drop_index(op.f('ix_users_subscription_id'), table_name='users')
    op.drop_index('ix_users_subscription_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index('ix_users_location_role', table_name='users')
    op.drop_index(op.f('ix_users_location_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_locations_subscription_id'), table_name='locations')
    op.drop_index('ix_locations_subscription_active', table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_exercises_subscription_active', table_name='exercises_library')
    op.drop_index(op.f('ix_exercises_library_subscription_id'), table_name='exercises_library')
    op.drop_index(op.f('ix_exercises_library_name'), table_name='exercises_library')
    op.drop_index(op.f('ix_exercises_library_is_global'), table_name='exercises_library')
    op.drop_index(op.f('ix_exercises_library_is_active'), table_name='exercises_library')
    op.drop_index(op.f('ix_exercises_library_id'), table_name='exercises_library')
    op.drop_index(op.f('ix_exercises_library_category'), table_name='exercises_library')
    op.drop_index('ix_exercises_global_active', table_name='exercises_library')
    op.drop_index('ix_exercises_category', table_name='exercises_library')
    op.drop_table('exercises_library')
    op.drop_index(op.f('ix_subscriptions_subscription_type'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_name'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
