"""add template system with exercises library and program assignments

Revision ID: 099175ffcad0
Revises: 98bdccbb6b23
Create Date: 2025-11-29 18:56:19.065973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099175ffcad0'
down_revision: Union[str, None] = '98bdccbb6b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_assignments_client_active', 'program_assignments', ['client_id', 'is_active'], unique=False)
    op.create_index('ix_assignments_subscription', 'program_assignments', ['subscription_id'], unique=False)
    op.create_index('ix_assignments_template', 'program_assignments', ['template_id'], unique=False)
    op.create_index(op.f('ix_program_assignments_client_id'), 'program_assignments', ['client_id'], unique=False)
    op.create_index(op.f('ix_program_assignments_id'), 'program_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_program_assignments_is_active'), 'program_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_program_assignments_program_id'), 'program_assignments', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_assignments_start_date'), 'program_assignments', ['start_date'], unique=False)
    op.create_index(op.f('ix_program_assignments_status'), 'program_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_program_assignments_template_id'), 'program_assignments', ['template_id'], unique=False)
    op.add_column('program_day_exercises', sa.Column('exercise_id', app.models.base.GUID(), nullable=False))
    op.add_column('program_day_exercises', sa.Column('subscription_id', app.models.base.GUID(), nullable=False))
    op.add_column('program_day_exercises', sa.Column('exercise_order', sa.Integer(), nullable=False))
    op.add_column('program_day_exercises', sa.Column('reps_min', sa.Integer(), nullable=True))
    op.add_column('program_day_exercises', sa.Column('reps_max', sa.Integer(), nullable=True))
    op.add_column('program_day_exercises', sa.Column('reps_target', sa.Integer(), nullable=True))
    op.add_column('program_day_exercises', sa.Column('load_type', sa.String(length=50), nullable=True))
    op.add_column('program_day_exercises', sa.Column('load_value', sa.Float(), nullable=True))
    op.add_column('program_day_exercises', sa.Column('load_unit', sa.String(length=20), nullable=True))
    op.add_column('program_day_exercises', sa.Column('tempo', sa.String(length=20), nullable=True))
    op.add_column('program_day_exercises', sa.Column('rest_seconds', sa.Integer(), nullable=True))
    op.add_column('program_day_exercises', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('program_day_exercises', sa.Column('rpe_target', sa.Float(), nullable=True))
    op.add_column('program_day_exercises', sa.Column('coaching_cues', sa.Text(), nullable=True))
    op.add_column('program_day_exercises', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('program_day_exercises', sa.Column('actual_sets', sa.Integer(), nullable=True))
    op.add_column('program_day_exercises', sa.Column('actual_reps', sa.Integer(), nullable=True))
    op.add_column('program_day_exercises', sa.Column('actual_weight', sa.Float(), nullable=True))
    op.add_column('program_day_exercises', sa.Column('actual_rpe', sa.Float(), nullable=True))
    op.add_column('program_day_exercises', sa.Column('completion_date', sa.String(length=50), nullable=True))
    op.alter_column('program_day_exercises', 'percentage_1rm',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_program_day_exercises_exercise_name', table_name='program_day_exercises')
    op.drop_index('ix_program_day_exercises_name', table_name='program_day_exercises')
    op.drop_index('ix_program_day_exercises_day_order', table_name='program_day_exercises')
    op.create_index('ix_program_day_exercises_day_order', 'program_day_exercises', ['program_day_id', 'exercise_order'], unique=False)
    op.create_index('ix_program_day_exercises_exercise', 'program_day_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_program_day_exercises_exercise_id'), 'program_day_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_program_day_exercises_subscription_id'), 'program_day_exercises', ['subscription_id'], unique=False)
    op.create_index('ix_program_day_exercises_unique_order', 'program_day_exercises', ['program_day_id', 'exercise_order'], unique=True)
    op.create_foreign_key(None, 'program_day_exercises', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'program_day_exercises', 'exercises_library', ['exercise_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('program_day_exercises', 'exercise_name')
    op.drop_column('program_day_exercises', 'reps')
    op.drop_column('program_day_exercises', 'order')
    op.drop_column('program_day_exercises', 'weight_lbs')
    op.add_column('program_days', sa.Column('subscription_id', app.models.base.GUID(), nullable=False))
    op.add_column('program_days', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('program_days', sa.Column('day_type', sa.String(length=50), nullable=True))
    op.add_column('program_days', sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('program_days', sa.Column('warm_up_notes', sa.Text(), nullable=True))
    op.add_column('program_days', sa.Column('cool_down_notes', sa.Text(), nullable=True))
    op.alter_column('program_days', 'suggested_day_of_week',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_program_days_subscription_id'), 'program_days', ['subscription_id'], unique=False)
    op.create_foreign_key(None, 'program_days', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    op.add_column('program_weeks', sa.Column('subscription_id', app.models.base.GUID(), nullable=False))
    op.add_column('program_weeks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('program_weeks', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('program_weeks', sa.Column('focus_area', sa.String(length=100), nullable=True))
    op.alter_column('program_weeks', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_program_weeks_subscription_id'), 'program_weeks', ['subscription_id'], unique=False)
    op.create_foreign_key(None, 'program_weeks', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    op.add_column('programs', sa.Column('program_type', sa.String(length=50), nullable=True))
    op.add_column('programs', sa.Column('difficulty_level', sa.String(length=50), nullable=True))
    op.add_column('programs', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.add_column('programs', sa.Column('template_version', sa.Integer(), nullable=False))
    op.add_column('programs', sa.Column('parent_template_id', app.models.base.GUID(), nullable=True))
    op.add_column('programs', sa.Column('required_parameters', app.models.subscription.JSONBType(), nullable=False))
    op.add_column('programs', sa.Column('optional_parameters', app.models.subscription.JSONBType(), nullable=False))
    op.add_column('programs', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('programs', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('programs', sa.Column('tags', app.models.subscription.JSONBType(), nullable=False))
    op.add_column('programs', sa.Column('goals', app.models.subscription.JSONBType(), nullable=True))
    op.add_column('programs', sa.Column('target_gender', sa.String(length=20), nullable=True))
    op.add_column('programs', sa.Column('equipment_required', app.models.subscription.JSONBType(), nullable=True))
    op.add_column('programs', sa.Column('times_assigned', sa.Integer(), nullable=False))
    op.add_column('programs', sa.Column('average_completion_rate', sa.Float(), nullable=True))
    op.add_column('programs', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('programs', sa.Column('price_cents', sa.Integer(), nullable=True))
    op.add_column('programs', sa.Column('revenue_share_pct', sa.Float(), nullable=True))
    op.add_column('programs', sa.Column('archived_at', sa.String(length=50), nullable=True))
    op.alter_column('programs', 'builder_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('programs', 'algorithm_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('programs', 'input_data',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('ix_programs_public_builder', table_name='programs')
    op.create_index('ix_programs_default_type', 'programs', ['is_default', 'program_type'], unique=False)
    op.create_index(op.f('ix_programs_is_default'), 'programs', ['is_default'], unique=False)
    op.create_index(op.f('ix_programs_program_type'), 'programs', ['program_type'], unique=False)
    op.create_index('ix_programs_public_type', 'programs', ['is_public', 'program_type'], unique=False)
    op.create_foreign_key(None, 'programs', 'programs', ['parent_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'programs', type_='foreignkey')
    op.drop_index('ix_programs_public_type', table_name='programs')
    op.drop_index(op.f('ix_programs_program_type'), table_name='programs')
    op.drop_index(op.f('ix_programs_is_default'), table_name='programs')
    op.drop_index('ix_programs_default_type', table_name='programs')
    op.create_index('ix_programs_public_builder', 'programs', ['is_public', 'builder_type'], unique=False)
    op.alter_column('programs', 'input_data',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('programs', 'algorithm_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('programs', 'builder_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('programs', 'archived_at')
    op.drop_column('programs', 'revenue_share_pct')
    op.drop_column('programs', 'price_cents')
    op.drop_column('programs', 'average_rating')
    op.drop_column('programs', 'average_completion_rate')
    op.drop_column('programs', 'times_assigned')
    op.drop_column('programs', 'equipment_required')
    op.drop_column('programs', 'target_gender')
    op.drop_column('programs', 'goals')
    op.drop_column('programs', 'tags')
    op.drop_column('programs', 'video_url')
    op.drop_column('programs', 'thumbnail_url')
    op.drop_column('programs', 'optional_parameters')
    op.drop_column('programs', 'required_parameters')
    op.drop_column('programs', 'parent_template_id')
    op.drop_column('programs', 'template_version')
    op.drop_column('programs', 'is_default')
    op.drop_column('programs', 'difficulty_level')
    op.drop_column('programs', 'program_type')
    op.drop_constraint(None, 'program_weeks', type_='foreignkey')
    op.drop_index(op.f('ix_program_weeks_subscription_id'), table_name='program_weeks')
    op.alter_column('program_weeks', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('program_weeks', 'focus_area')
    op.drop_column('program_weeks', 'notes')
    op.drop_column('program_weeks', 'description')
    op.drop_column('program_weeks', 'subscription_id')
    op.drop_constraint(None, 'program_days', type_='foreignkey')
    op.drop_index(op.f('ix_program_days_subscription_id'), table_name='program_days')
    op.alter_column('program_days', 'suggested_day_of_week',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('program_days', 'cool_down_notes')
    op.drop_column('program_days', 'warm_up_notes')
    op.drop_column('program_days', 'estimated_duration_minutes')
    op.drop_column('program_days', 'day_type')
    op.drop_column('program_days', 'description')
    op.drop_column('program_days', 'subscription_id')
    op.add_column('program_day_exercises', sa.Column('weight_lbs', sa.INTEGER(), nullable=True))
    op.add_column('program_day_exercises', sa.Column('order', sa.INTEGER(), nullable=False))
    op.add_column('program_day_exercises', sa.Column('reps', sa.INTEGER(), nullable=False))
    op.add_column('program_day_exercises', sa.Column('exercise_name', sa.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'program_day_exercises', type_='foreignkey')
    op.drop_constraint(None, 'program_day_exercises', type_='foreignkey')
    op.drop_index('ix_program_day_exercises_unique_order', table_name='program_day_exercises')
    op.drop_index(op.f('ix_program_day_exercises_subscription_id'), table_name='program_day_exercises')
    op.drop_index(op.f('ix_program_day_exercises_exercise_id'), table_name='program_day_exercises')
    op.drop_index('ix_program_day_exercises_exercise', table_name='program_day_exercises')
    op.drop_index('ix_program_day_exercises_day_order', table_name='program_day_exercises')
    op.create_index('ix_program_day_exercises_day_order', 'program_day_exercises', ['program_day_id', 'order'], unique=False)
    op.create_index('ix_program_day_exercises_name', 'program_day_exercises', ['exercise_name'], unique=False)
    op.create_index('ix_program_day_exercises_exercise_name', 'program_day_exercises', ['exercise_name'], unique=False)
    op.alter_column('program_day_exercises', 'percentage_1rm',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('program_day_exercises', 'completion_date')
    op.drop_column('program_day_exercises', 'actual_rpe')
    op.drop_column('program_day_exercises', 'actual_weight')
    op.drop_column('program_day_exercises', 'actual_reps')
    op.drop_column('program_day_exercises', 'actual_sets')
    op.drop_column('program_day_exercises', 'is_completed')
    op.drop_column('program_day_exercises', 'coaching_cues')
    op.drop_column('program_day_exercises', 'rpe_target')
    op.drop_column('program_day_exercises', 'duration_seconds')
    op.drop_column('program_day_exercises', 'rest_seconds')
    op.drop_column('program_day_exercises', 'tempo')
    op.drop_column('program_day_exercises', 'load_unit')
    op.drop_column('program_day_exercises', 'load_value')
    op.drop_column('program_day_exercises', 'load_type')
    op.drop_column('program_day_exercises', 'reps_target')
    op.drop_column('program_day_exercises', 'reps_max')
    op.drop_column('program_day_exercises', 'reps_min')
    op.drop_column('program_day_exercises', 'exercise_order')
    op.drop_column('program_day_exercises', 'subscription_id')
    op.drop_column('program_day_exercises', 'exercise_id')
    op.drop_index(op.f('ix_program_assignments_template_id'), table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_status'), table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_start_date'), table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_program_id'), table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_is_active'), table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_id'), table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_client_id'), table_name='program_assignments')
    op.drop_index('ix_assignments_template', table_name='program_assignments')
    op.drop_index('ix_assignments_subscription', table_name='program_assignments')
    op.drop_index('ix_assignments_client_active', table_name='program_assignments')
    # ### end Alembic commands ###
