"""Initial schema

Revision ID: 6e08e008e7e4
Revises: 
Create Date: 2025-11-15 09:36:48.223228

"""
from typing import Sequence, Union

# Import custom types
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent.parent.parent))

from app.models.base import GUID
from app.models.subscription import JSONBType

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e08e008e7e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subscription_type', sa.Enum('INDIVIDUAL', 'GYM', 'ENTERPRISE', name='subscription_type_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELLED', name='subscription_status_enum', native_enum=False), nullable=False),
    sa.Column('features', JSONBType(), nullable=False),
    sa.Column('limits', JSONBType(), nullable=False),
    sa.Column('billing_info', JSONBType(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', GUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_name'), 'subscriptions', ['name'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscription_type'), 'subscriptions', ['subscription_type'], unique=False)
    op.create_table('locations',
    sa.Column('subscription_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', JSONBType(), nullable=True),
    sa.Column('contact_info', JSONBType(), nullable=True),
    sa.Column('settings', JSONBType(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index('ix_locations_subscription_active', 'locations', ['subscription_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_locations_subscription_id'), 'locations', ['subscription_id'], unique=False)
    op.create_table('users',
    sa.Column('subscription_id', GUID(), nullable=True),
    sa.Column('location_id', GUID(), nullable=True),
    sa.Column('role', sa.Enum('APPLICATION_SUPPORT', 'SUBSCRIPTION_ADMIN', 'COACH', 'CLIENT', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile', JSONBType(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_location_id'), 'users', ['location_id'], unique=False)
    op.create_index('ix_users_location_role', 'users', ['location_id', 'role'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_subscription_active', 'users', ['subscription_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_subscription_id'), 'users', ['subscription_id'], unique=False)
    op.create_index('ix_users_subscription_role', 'users', ['subscription_id', 'role'], unique=False)
    op.create_table('audit_log',
    sa.Column('subscription_id', GUID(), nullable=True),
    sa.Column('location_id', GUID(), nullable=True),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'ACCESS', 'PERMISSION_DENIED', 'PASSWORD_RESET', 'ROLE_CHANGE', name='audit_action_enum', native_enum=False), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', GUID(), nullable=True),
    sa.Column('changes', JSONBType(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('extra_metadata', JSONBType(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_timestamp', 'audit_log', ['action', 'timestamp'], unique=False)
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_location_id'), 'audit_log', ['location_id'], unique=False)
    op.create_index(op.f('ix_audit_log_subscription_id'), 'audit_log', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_index('ix_audit_subscription_timestamp', 'audit_log', ['subscription_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_user_timestamp', 'audit_log', ['user_id', 'timestamp'], unique=False)
    op.create_table('coach_client_assignments',
    sa.Column('subscription_id', GUID(), nullable=False),
    sa.Column('location_id', GUID(), nullable=True),
    sa.Column('coach_id', GUID(), nullable=False),
    sa.Column('client_id', GUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_client_active', 'coach_client_assignments', ['client_id', 'is_active'], unique=False)
    op.create_index('ix_assignments_coach_active', 'coach_client_assignments', ['coach_id', 'is_active'], unique=False)
    op.create_index('ix_assignments_location_active', 'coach_client_assignments', ['location_id', 'is_active'], unique=False)
    op.create_index('ix_assignments_subscription_active', 'coach_client_assignments', ['subscription_id', 'is_active'], unique=False)
    op.create_index('ix_assignments_unique', 'coach_client_assignments', ['coach_id', 'client_id', 'is_active'], unique=True)
    op.create_index(op.f('ix_coach_client_assignments_client_id'), 'coach_client_assignments', ['client_id'], unique=False)
    op.create_index(op.f('ix_coach_client_assignments_coach_id'), 'coach_client_assignments', ['coach_id'], unique=False)
    op.create_index(op.f('ix_coach_client_assignments_id'), 'coach_client_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_coach_client_assignments_location_id'), 'coach_client_assignments', ['location_id'], unique=False)
    op.create_index(op.f('ix_coach_client_assignments_subscription_id'), 'coach_client_assignments', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coach_client_assignments_subscription_id'), table_name='coach_client_assignments')
    op.drop_index(op.f('ix_coach_client_assignments_location_id'), table_name='coach_client_assignments')
    op.drop_index(op.f('ix_coach_client_assignments_id'), table_name='coach_client_assignments')
    op.drop_index(op.f('ix_coach_client_assignments_coach_id'), table_name='coach_client_assignments')
    op.drop_index(op.f('ix_coach_client_assignments_client_id'), table_name='coach_client_assignments')
    op.drop_index('ix_assignments_unique', table_name='coach_client_assignments')
    op.drop_index('ix_assignments_subscription_active', table_name='coach_client_assignments')
    op.drop_index('ix_assignments_location_active', table_name='coach_client_assignments')
    op.drop_index('ix_assignments_coach_active', table_name='coach_client_assignments')
    op.drop_index('ix_assignments_client_active', table_name='coach_client_assignments')
    op.drop_table('coach_client_assignments')
    op.drop_index('ix_audit_user_timestamp', table_name='audit_log')
    op.drop_index('ix_audit_subscription_timestamp', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_subscription_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_location_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_index('ix_audit_action_timestamp', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_users_subscription_role', table_name='users')
    op.drop_index(op.f('ix_users_subscription_id'), table_name='users')
    op.drop_index('ix_users_subscription_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index('ix_users_location_role', table_name='users')
    op.drop_index(op.f('ix_users_location_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_locations_subscription_id'), table_name='locations')
    op.drop_index('ix_locations_subscription_active', table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_subscriptions_subscription_type'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_name'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
