"""add password_must_be_changed field to users

Revision ID: 98bdccbb6b23
Revises: 6e08e008e7e4
Create Date: 2025-11-29 17:33:27.250878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98bdccbb6b23'
down_revision: Union[str, None] = '6e08e008e7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_must_be_changed', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_must_be_changed')
    # ### end Alembic commands ###
